- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zones: surya-devops.site
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      region: us-east-1
      name: "{{item}}"
      security_group: allow-everything
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{item}}"
    loop:
    - "{{instances}}"
    register: ec2_instanes_info

  - name: print output
    ansible.builtin.debug:
      msg: "Output {{ec2_instances_info}}"


  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{zones}}"
      record: "{{item}}.{{zone}}"
      type: A
      value: "{{item.private_ip_address}}"
      overwrite: true
      ttl: 5
    loop:
    - "{{ec2_instances_info.results.instances}}"