- name: delete {{app_location}} directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent
  
- name: create {{app_location}} directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

- name: download & extract {{component}} code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
    dest: "{{app_location}}"
    remote_src: true

- name: Check if code is extracted
  ansible.builtin.stat:
    path: "{{ app_location }}/backend.zip"  # Replace with an actual expected file
  register: code_status

- name: Debug extracted code
  ansible.builtin.debug:
    msg: "Code extracted: {{ code_status.stat.exists }}"